name: 'Test'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3.0.0'

      - name: 'Use Node.js'
        uses: 'actions/setup-node@v3.1.0'
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: 'Install'
        run: 'npm install'

      - name: 'Test'
        run: 'npm run test'
